/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Generated by Next.js. Committed so `npm run typecheck` works on a fresh
// clone without a prior build; `next dev` / `next build` rewrites it in place.
