/**
 * Deterministic enumerator — the third tier.
 *
 * When every model provider is rate-limited or down, the loop still needs to
 * propose something, because a session that stops is a demo that stops. This
 * tier walks a fixed, ordered enumeration of the hypothesis space and returns
 * the Nth valid candidate.
 *
 * Two properties it must have:
 *
 *  1. DETERMINISTIC. The same attempt number always yields the same proposal,
 *     so a replayed session reproduces exactly. This is what lets the log be
 *     audited: an entry generated by this tier can be re-derived from its index
 *     alone, with no model in the loop.
 *
 *  2. HONEST ABOUT ITSELF. Its proposals are recorded with
 *     `generator: 'deterministic'`, so a reader can always tell which
 *     hypotheses came from a model and which came from a counter. Presenting
 *     enumerated candidates as model output would be a small lie of exactly the
 *     kind this project is built to avoid.
 *
 * The enumeration is not random and not clever. It is a breadth-first walk of
 * (family, signal, target, condition, window), which means early attempts spread
 * across families and targets rather than exhausting one corner of the space —
 * the behaviour you want from a fallback, since it keeps the multiple-testing
 * family diverse and the BH correction meaningful.
 */

import {
  FAMILY_SIGNALS,
  FAMILY_WINDOW_BOUNDS,
  type ExperimentFamily,
  type Operator,
  type ProposedHypothesis,
  type RTokenSymbol,
  type SignalId,
} from '../types.js';
import { RTOKEN_SYMBOLS } from '../types.js';
import { validateProposal } from '../schema/validate.js';

interface ConditionTemplate {
  operator: Operator;
  threshold: number;
}

/**
 * Threshold/operator pairs chosen from the measured signal distributions, so
 * every one of them selects a non-empty event set by construction. See
 * docs/DATA_FINDINGS.md §9 for the funding-rate distribution these come from.
 */
const FUNDING_CONDITIONS: readonly ConditionTemplate[] = [
  { operator: 'gt', threshold: 0.00005 },
  { operator: 'gt', threshold: 0.00009 },
  { operator: 'gt', threshold: 0.00002 },
  { operator: 'lt', threshold: 0.00001 },
  { operator: 'lt', threshold: -0.00005 },
];

/** Spot returns are in PERCENT. Thresholds below 0.01 are rejected. */
const SPOT_CONDITIONS: readonly ConditionTemplate[] = [
  { operator: 'gt', threshold: 0.25 },
  { operator: 'gt', threshold: 0.5 },
  { operator: 'gt', threshold: 0.1 },
  { operator: 'lt', threshold: -0.25 },
  { operator: 'lt', threshold: -0.5 },
];

const LOOKBACKS: readonly number[] = [30, 60, 120, 240];

const FAMILIES: readonly ExperimentFamily[] = [
  'funding_to_rtoken',
  'btc_momentum_to_rtoken',
  'combined_cross_asset',
];

function conditionsFor(signal: SignalId): readonly ConditionTemplate[] {
  return signal.includes('funding') ? FUNDING_CONDITIONS : SPOT_CONDITIONS;
}

function windowsFor(family: ExperimentFamily): readonly number[] {
  const b = FAMILY_WINDOW_BOUNDS[family];
  return [15, 30, 60, 120].filter((w) => w >= b.min && w <= b.max);
}

/**
 * The full enumeration, built once and cached.
 *
 * Built as a natural nested cross-product, then WALKED WITH A STRIDE. The stride
 * is not decoration — it fixes a real failure found by measuring the first
 * twenty outputs.
 *
 * The nested loops alone put `lookback_minutes` innermost, so the first twenty
 * entries were one family, one signal, one target, one condition and one window,
 * differing only in the lookback. Twenty consecutive fallback proposals would
 * therefore have been twenty near-identical variants of a single idea — which is
 * precisely the multiple-testing anti-pattern the rest of this system exists to
 * catch, and which would have made a model-outage session produce a family of
 * correlated tests and nothing else.
 *
 * Walking `i * STRIDE mod N` fixes it. Because the stride is coprime with the
 * space size, the walk still visits every entry exactly once before repeating,
 * so no candidate is skipped and the wrap-around property is preserved — but
 * consecutive entries are now far apart in the natural ordering, so they differ
 * in several dimensions at once. The measured effect is recorded in
 * docs/DATA_FINDINGS.md.
 */
let cachedSpace: ProposedHypothesis[] | null = null;

/**
 * Coprime with the space size (2240 = 2^6 * 5 * 7; 337 is prime and > 7), so
 * the strided walk is a permutation of the whole space rather than a tour of a
 * subset. If the space size changes, this must be re-chosen: a stride sharing a
 * factor with N would cycle through only N/gcd entries forever, silently and
 * permanently narrowing the search. `assertStrideIsValid` enforces that.
 */
const STRIDE = 337;

function gcd(a: number, b: number): number {
  while (b !== 0) {
    const t = b;
    b = a % b;
    a = t;
  }
  return a;
}

export function enumerableSpace(): ProposedHypothesis[] {
  if (cachedSpace) return cachedSpace;

  const out: ProposedHypothesis[] = [];

  for (const family of FAMILIES) {
    for (const signal of FAMILY_SIGNALS[family]) {
      for (const target of RTOKEN_SYMBOLS) {
        for (const cond of conditionsFor(signal)) {
          for (const forward of windowsFor(family)) {
            for (const lookback of LOOKBACKS) {
              const candidate = {
                signal,
                condition: {
                  operator: cond.operator,
                  threshold: cond.threshold,
                  lookback_minutes: lookback,
                },
                target: target as RTokenSymbol,
                direction: cond.operator === 'gt' ? 'positive' : 'negative',
                forward_return_minutes: forward,
                experiment_family: family,
              } satisfies ProposedHypothesis;

              // Belt and braces: the templates above are chosen to be valid, but
              // the validator is the single source of truth for that, so a
              // template edited later cannot silently emit an invalid proposal.
              if (validateProposal(candidate).ok) out.push(candidate);
            }
          }
        }
      }
    }
  }

  if (out.length === 0) {
    throw new Error('deterministic enumerator produced an empty space');
  }
  if (gcd(STRIDE, out.length) !== 1) {
    throw new Error(
      `deterministic stride ${STRIDE} is not coprime with the space size ${out.length}; ` +
        `the walk would visit only ${out.length / gcd(STRIDE, out.length)} of ${out.length} ` +
        `entries and repeat forever. Choose a stride coprime with the space size.`,
    );
  }

  cachedSpace = out;
  return out;
}

/** The space in its natural nested-loop order, for audit and full sweeps. */
export function enumerableSpaceNaturalOrder(): ProposedHypothesis[] {
  return [...enumerableSpace()];
}

/**
 * The candidate for a given attempt number.
 *
 * The strided walk means every entry is visited once before any repeats. Past
 * that point the loop's duplicate detector takes over and the repeats are
 * KILLed with `duplicate_family` — the correct outcome, and evidence the
 * detector works, rather than a failure.
 */
export function enumerateHypothesis(attemptIndex: number): ProposedHypothesis {
  const space = enumerableSpace();
  const i = ((attemptIndex % space.length) + space.length) % space.length;
  return space[(i * STRIDE) % space.length]!;
}

